const actionTypes = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  COLLECT_INTEREST: 'COLLECT_INTEREST',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  CHANGE_ACC_TYPE: 'CHANGE_ACC_TYPE',
  TOGGLE_AUTH: 'TOGGLE_AUTH',
  FETCH_POSTS_REQUEST: 'FETCH_POSTS_REQUEST',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',
};
export default actionTypes;
