const actionTypes = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  COLLECT_INTEREST: 'COLLECT_INTEREST',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  CHANGE_ACC_TYPE: 'CHANGE_ACC_TYPE',
  TOGGLE_AUTH: 'TOGGLE_AUTH',
};
export default actionTypes;
